config/routes.rb
Rails.application.routes.draw do
  resources :videos, only: [:index, :show]

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  field :user, type: String
  field :text, type: String
  field :video_id, type: Integer

  validates :video_id, presence: true
  validates :user,     presence: true
  validates :text,     presence: true
end

app/models/video.rb
class Video < OpenStruct
  SITE = 'http://localhost:3000'

  def self.all
    get_json('/videos').map do |attrs|
      new attrs
    end
  end

  def self.find(id)
    new get_json("/videos/#{id}")
  end

  def comments
    Comment.where(video_id: self.id)
  end

  def to_param
    self.id.to_s if self.id
  end

  private
  def self.get_json(path)
    uri = URI('http://localhost:3000/')
    uri.path = path

    req = Net::HTTP::Get.new(uri)
    req['ACCEPT'] = 'application/json'

    res = Net::HTTP.start(uri.hostname, uri.port) {|http|
      http.request(req)
    }

    JSON.parse(res.body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
  end

  def show
    @video = Video.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # TODO: video url must came from API
  def video_url_of(video, format)
    "#{Video::SITE}/videos/development/#{video.id}/#{video.id}.#{format}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoConsumptionExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/videos/index.html.erb
<h1>Videos#index</h1>

<% @videos.each do |video| %>
  <%= link_to video.title, video_path(video) %>
<% end %>

app/views/videos/show.html.erb
<h1><%= @video.title %></h1>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<video width="320" height="240" controls>
  <source src="<%= video_url_of(@video, :mp4) %>" type="video/mp4" />
  <source src="<%= video_url_of(@video, :ogg) %>" type="video/ogg" />
Your browser does not support the video tag.
</video>

<ul id="comments_list">
  <% @video.comments.each do |comment| %>
    <li class="comment">
      <span>by: <%= comment.user %></span>
      <%= comment.text %>
    </li>
  <% end %>
</ul>